---
title: Tamil Christian Fellowship, Melbourne
timezone: Australia/Melbourne
# collections:
#   about-staff:
#     title: About Staff
#     output: false
#   carousel:
#     title: Carousel
#     output: true
#   news-items:
#     title: News Items
#     output: false
#   posts:
#     title: Posts
#     output: true
#   primary-partners:
#     title: Primary Partners
#     output: true
#   programs:
#     title: Programs
#     output: false
#   secondary-partners:
#     title: Secondary Partners
#     output: true
#   uploads:
#     title: Uploads
#     output: true
# defaults:
# - scope:
#     path: ''
#     type: news-items
#   values:
#     heading:
#     link:
#     image:
# - scope:
#     path: ''
#     type: programs
#   values:
#     name:
#     short:
#     icon:
#     cta:
encoding: utf-8
version: v1
favicon: images/Logo.png
tv: 4.5.3
markdown: kramdown
exclude:
- node_modules
- gulpfile.js
# social:
# - name: Facebook
#   link: https://www.facebook.com/Bartlom%C3%A9-Soccer-Academy-1699026550336895/
# - name: YouTube
#   link: https://www.youtube.com/channel/UCzMQUxx0ocF0OJqvfqQ1Khw
# - name: Instagram
#   link: http://instagram.com/bartlomesocceracademy
# nav:
# - name: Programs
#   link: "/#programs"
# - name: About
#   drop:
#   - name: BSA
#     link: "/#about-bsa"
#   - name: Staff
#     link: "/#about-staff"
# - name: Contact
#   link: "/#contact"
